name: CI/CD for DigitalOcean Deployment

on:
  push:
    branches:
      - main  # This triggers the workflow when you push to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment
    
    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Step 2: Set up PHP (using PHP version 7.4 as an example, adjust if needed)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Adjust the PHP version to match your project
          extensions: mbstring, xml, curl  # Add any required extensions here

      # Step 3: Install PHP dependencies using Composer
      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install  # Make sure you have a composer.json in your repo

      # Step 4: Build the project (optional; use this if you need to build your project)
      # If you have a build step, like minifying assets, add it here.
      - name: Build project
        run: |
          # Example: If you need to build assets or do other tasks, add commands here
          echo "No build step required for PHP"

      # Step 5: Deploy to DigitalOcean (you'll need to set up a DigitalOcean API token)
      - name: Deploy to DigitalOcean
        run: |
          curl -sL https://cli.digitalocean.com/install.sh | bash
          doctl auth init -t ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          doctl apps create-deployment --app ${{ secrets.DIGITALOCEAN_APP_ID }}
